# Generated by Django 5.2.1 on 2025-07-19 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='citytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'City Translation'},
        ),
    ]
