# Generated by Django 5.2.1 on 2025-07-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_alter_city_options_alter_citytranslation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citytranslation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City name'),
        ),
    ]
