# Generated by Django 5.2.1 on 2026-03-28 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_alter_citytranslation_name'),
        ('telegram', '0017_add_multi_city_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('telegram.channel',),
        ),
    ]
