# Generated by Django 5.2.1 on 2026-05-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0004_add_multi_city_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AddField(
            model_name='city',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
