# Generated by Django 5.2.1 on 2026-05-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0005_alter_city_options_city_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='order',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='Порядок'),
        ),
    ]
