# Generated by Django 5.2.1 on 2026-03-16 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacancy', '0023_delete_vacancyuserfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonobankPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('order_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('amount', models.PositiveBigIntegerField(help_text='Amount in kopecks (smallest unit)')),
                ('final_amount', models.PositiveBigIntegerField(blank=True, null=True)),
                ('ccy', models.IntegerField(default=980, help_text='Currency code (980=UAH)')),
                ('status', models.CharField(choices=[('created', 'Created'), ('processing', 'Processing'), ('hold', 'Hold'), ('success', 'Success'), ('failure', 'Failure'), ('reversed', 'Reversed'), ('expired', 'Expired')], default='created', max_length=20)),
                ('page_url', models.URLField(blank=True, max_length=512)),
                ('mono_modified_date', models.DateTimeField(blank=True, null=True)),
                ('masked_pan', models.CharField(blank=True, max_length=20)),
                ('raw_webhook_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monobank_payments', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monobank_payments', to='vacancy.vacancy')),
            ],
            options={
                'verbose_name': 'Monobank Payment',
                'verbose_name_plural': 'Monobank Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
