# Generated by Django 5.2.1 on 2026-04-01 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monobankpayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Платіж Monobank', 'verbose_name_plural': 'Платежі Monobank'},
        ),
    ]
