# Generated by Django 5.2.1 on 2025-07-19 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_alter_city_options_alter_citytranslation_options'),
        ('work', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userworkprofile',
            options={'verbose_name': 'User work profile', 'verbose_name_plural': 'User work profiles'},
        ),
        migrations.AlterField(
            model_name='userworkprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='city.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='userworkprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='userworkprofile',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Is completed'),
        ),
        migrations.AlterField(
            model_name='userworkprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='userworkprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('employer', 'Employer'), ('worker', 'Worker')], max_length=20, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='userworkprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
