# Generated by Django 5.2.1 on 2026-01-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_alter_userworkprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('employer', 'Роботодавець'), ('worker', 'Працівник')], max_length=20, unique=True)),
                ('title', models.CharField(default='Договір о співпраці', max_length=255)),
                ('text', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
