# Generated by Django 5.2.1 on 2026-03-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_alter_userworkprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('employer', 'Agreement for Employer'), ('worker', 'Agreement for Worker'), ('offer', 'Public offer and Privacy policy')], max_length=20, unique=True, verbose_name='Type')),
                ('title', models.CharField(default='Договір о співпраці', max_length=255, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Agreement text',
                'verbose_name_plural': 'Agreement texts',
            },
        ),
        migrations.AddField(
            model_name='userworkprofile',
            name='agreement_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userworkprofile',
            name='agreement_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
