# Generated by Django 5.2.1 on 2026-01-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_agreementtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkprofile',
            name='agreement_accepted',
            field=models.BooleanField(default=False, verbose_name='Agreement accepted'),
        ),
        migrations.AddField(
            model_name='userworkprofile',
            name='agreement_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Agreement accepted at'),
        ),
    ]
