# Generated by Django 5.2.1 on 2026-03-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_agreementtext_userworkprofile_agreement_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworkprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('employer', 'Employer'), ('worker', 'Worker'), ('administrator', 'Administrator')], max_length=20, null=True, verbose_name='Role'),
        ),
    ]
