# Generated by Django 5.2.1 on 2026-03-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0004_add_multi_city_fields'),
        ('work', '0004_add_administrator_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkprofile',
            name='allowed_cities',
            field=models.ManyToManyField(blank=True, help_text='Cities where employer can post vacancies (in addition to main city)', related_name='allowed_employers', to='city.city', verbose_name='Allowed cities'),
        ),
        migrations.AddField(
            model_name='userworkprofile',
            name='multi_city_enabled',
            field=models.BooleanField(default=False, help_text='Allow employer to post vacancies in multiple cities', verbose_name='Multi-city enabled'),
        ),
    ]
