# Generated by Django 5.2.1 on 2026-04-01 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_add_multi_city_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreementtext',
            options={'verbose_name': 'Текст угоди', 'verbose_name_plural': 'Тексти угод'},
        ),
    ]
