# Generated by Django 5.2.1 on 2026-04-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_alter_agreementtext_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('employer', 'Employer'), ('worker', 'Worker')], max_length=20, verbose_name='Role')),
                ('question', models.CharField(max_length=500, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('image', models.ImageField(blank=True, null=True, upload_to='faq/', verbose_name='Image')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Video URL (YouTube, etc.)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'FAQ запис',
                'verbose_name_plural': 'FAQ записи',
                'ordering': ['role', 'order'],
            },
        ),
    ]
