# Generated by Django 5.2.1 on 2026-06-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_faqitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkprofile',
            name='auto_approve_vacancy',
            field=models.BooleanField(default=False, help_text='Automatically approve vacancies without admin moderation', verbose_name='Auto-approve vacancies'),
        ),
    ]
