# Generated by Django 5.2.1 on 2026-06-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_auto_approve_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_threshold', models.PositiveIntegerField(default=5, help_text='Кількість віртуальних голосів для нових користувачів. Рекомендовано: 3-10.', verbose_name='Поріг рейтингу (Байєс)')),
            ],
            options={
                'verbose_name': 'Налаштування рейтингу',
                'verbose_name_plural': 'Налаштування рейтингу',
            },
        ),
    ]
