# Generated by Django 5.2.1 on 2026-06-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_ratingconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_fee_per_worker', models.PositiveIntegerField(default=100, help_text='Сума, яку платформа стягує з замовника за кожного фактично відпрацьованого працівника.', verbose_name='Сервісний збір за одного працівника (грн)')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплата',
            },
        ),
    ]
