# Generated by Django 5.2.1 on 2025-06-02 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_choice', models.CharField(choices=[('now', 'Now'), ('tomorrow', 'Tomorrow')], default='tomorrow', max_length=10, verbose_name='Date')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Any')], default='X', max_length=1, verbose_name='Preferred Gender')),
                ('people_count', models.PositiveIntegerField(verbose_name='Number of People')),
                ('has_passport', models.BooleanField(verbose_name='Has Passport')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('map_link', models.URLField(blank=True, verbose_name='Map Link')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Payment Amount')),
                ('payment_unit', models.CharField(choices=[('hour', 'Per hour'), ('shift', 'Per shift')], default='shift', max_length=10, verbose_name='Payment Type')),
                ('skills', models.TextField(verbose_name='Skills Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='vacancy.vacancy')),
            ],
        ),
    ]
