# Generated by Django 5.2.1 on 2025-06-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='date_choice',
        ),
    ]
