# Generated by Django 5.2.1 on 2025-06-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_remove_vacancy_date_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancystatushistory',
            name='previous_status',
        ),
    ]
