# Generated by Django 5.2.1 on 2025-06-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_remove_vacancystatushistory_previous_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancystatushistory',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
