# Generated by Django 5.2.1 on 2025-06-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0004_alter_vacancystatushistory_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], default='cash', max_length=10, verbose_name='Payment method'),
        ),
    ]
