# Generated by Django 5.2.1 on 2025-06-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0005_vacancy_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='date_choice',
            field=models.CharField(choices=[('now', 'Now'), ('tomorrow', 'Tomorrow')], default='now', max_length=10, verbose_name='Date choices'),
        ),
    ]
