# Generated by Django 5.2.1 on 2025-06-19 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_channel_invite_link'),
        ('vacancy', '0006_vacancy_date_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram.group'),
        ),
    ]
