# Generated by Django 5.2.1 on 2025-06-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0007_vacancy_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='map_link',
            field=models.URLField(blank=True, null=True, verbose_name='Map Link (is not required)'),
        ),
    ]
