# Generated by Django 5.2.1 on 2025-07-01 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0008_channelmessage'),
        ('vacancy', '0009_alter_vacancy_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram.channel'),
        ),
    ]
