# Generated by Django 5.2.1 on 2025-07-10 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0012_vacancyuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyUserCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirm', 'Confirm'), ('reject', 'Reject')], max_length=20)),
                ('call_type', models.CharField(choices=[('before_start', 'Before start'), ('start', 'Start'), ('after_start', 'After start')], max_length=20)),
                ('vacancy_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.vacancyuser')),
            ],
        ),
        migrations.DeleteModel(
            name='UserVacancyCall',
        ),
    ]
