# Generated by Django 5.2.1 on 2025-07-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0013_vacancyusercall_delete_uservacancycall'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyusercall',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancyusercall',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('confirm', 'Confirm'), ('reject', 'Reject')], default='sent', max_length=20),
        ),
    ]
