# Generated by Django 5.2.1 on 2025-07-10 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0014_vacancyusercall_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyusercall',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
