# Generated by Django 5.2.1 on 2025-07-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0015_alter_vacancyusercall_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyusercall',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
