# Generated by Django 5.2.1 on 2025-07-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0016_vacancyusercall_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
        migrations.AlterModelOptions(
            name='vacancystatushistory',
            options={'verbose_name': 'Status history', 'verbose_name_plural': 'Status history'},
        ),
        migrations.AlterModelOptions(
            name='vacancyuser',
            options={'verbose_name': 'User in vacancy', 'verbose_name_plural': 'Users in vacancy'},
        ),
        migrations.AlterModelOptions(
            name='vacancyusercall',
            options={'verbose_name': 'User call in vacancy', 'verbose_name_plural': 'User calls in vacancy'},
        ),
        migrations.AlterField(
            model_name='vacancyusercall',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('sent', 'Sent'), ('confirm', 'Confirm'), ('reject', 'Reject')], default='sent', max_length=20),
        ),
    ]
