# Generated by Django 5.2.1 on 2025-07-21 12:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0017_alter_vacancy_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancystatushistory',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Changed at'),
        ),
        migrations.AlterField(
            model_name='vacancystatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Changed by'),
        ),
        migrations.AlterField(
            model_name='vacancystatushistory',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='vacancystatushistory',
            name='new_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active')], max_length=20, verbose_name='New status'),
        ),
        migrations.AlterField(
            model_name='vacancystatushistory',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='vacancy.vacancy', verbose_name='Vacancy'),
        ),
        migrations.AlterField(
            model_name='vacancyuser',
            name='status',
            field=models.CharField(choices=[('creator', 'Creator'), ('administrator', 'Administrator'), ('member', 'Member'), ('restricted', 'Restricted'), ('left', 'Left'), ('kicked', 'Kicked'), ('ban', 'Ban'), ('unban', 'Unban')], default='member', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='vacancyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='vacancyuser',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='vacancy.vacancy', verbose_name='Vacancy'),
        ),
        migrations.AlterField(
            model_name='vacancyusercall',
            name='call_type',
            field=models.CharField(choices=[('before_start', 'Before start'), ('start', 'Start'), ('after_start', 'After start')], max_length=20, verbose_name='Call type'),
        ),
        migrations.AlterField(
            model_name='vacancyusercall',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='vacancyusercall',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('sent', 'Sent'), ('confirm', 'Confirm'), ('reject', 'Reject')], default='sent', max_length=20, verbose_name='Call status'),
        ),
        migrations.AlterField(
            model_name='vacancyusercall',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='vacancyusercall',
            name='vacancy_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.vacancyuser', verbose_name='Vacancy user'),
        ),
    ]
