# Generated by Django 5.2.1 on 2025-07-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0018_alter_vacancystatushistory_changed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
