# Generated by Django 5.2.1 on 2025-07-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0019_vacancy_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('closed', 'Closed')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='vacancystatushistory',
            name='new_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('closed', 'Closed')], max_length=20, verbose_name='New status'),
        ),
    ]
