# Generated by Django 5.2.1 on 2025-08-09 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0020_alter_vacancy_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyuser',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='vacancyuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='date_choice',
            field=models.CharField(choices=[('now', 'Today'), ('tomorrow', 'Tomorrow')], default='now', max_length=10, verbose_name='Date choices'),
        ),
        migrations.AlterField(
            model_name='vacancyuser',
            name='status',
            field=models.CharField(choices=[('creator', 'Creator'), ('administrator', 'Administrator'), ('owner', 'Owner'), ('member', 'Member'), ('restricted', 'Restricted'), ('left', 'Left'), ('kicked', 'Kicked'), ('ban', 'Ban'), ('unban', 'Unban')], default='member', max_length=20, verbose_name='Status'),
        ),
    ]
