# Generated by Django 5.2.1 on 2025-08-10 13:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0021_vacancyuser_created_at_vacancyuser_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyUserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created at')),
                ('vacancy_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.vacancyuser', verbose_name='Vacancy user')),
            ],
        ),
    ]
