# Generated by Django 5.2.1 on 2025-08-13 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0022_vacancyuserfeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VacancyUserFeedback',
        ),
    ]
