# Generated by Django 5.2.1 on 2026-03-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0023_delete_vacancyuserfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Contact phone'),
        ),
    ]
