# Generated by Django 5.2.1 on 2026-03-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0025_add_search_active_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='first_rollcall_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='search_stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='second_rollcall_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('closed', 'Closed'), ('stopped', 'Search stopped'), ('awaiting', 'Awaiting payment')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='vacancystatushistory',
            name='new_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('closed', 'Closed'), ('stopped', 'Search stopped'), ('awaiting', 'Awaiting payment')], max_length=20, verbose_name='New status'),
        ),
    ]
