# Generated by Django 5.2.1 on 2026-04-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0026_vacancy_closed_at_vacancy_first_rollcall_passed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancyuser',
            options={'verbose_name': 'Учасник вакансії', 'verbose_name_plural': 'Учасники вакансій'},
        ),
        migrations.AlterModelOptions(
            name='vacancyusercall',
            options={'verbose_name': 'Перекличка', 'verbose_name_plural': 'Переклички'},
        ),
        migrations.AlterField(
            model_name='vacancyusercall',
            name='call_type',
            field=models.CharField(choices=[('before_start', 'Before start'), ('start', 'Start'), ('after_start', 'After start'), ('join_confirm', 'Join confirm'), ('renewal_employer', 'Renewal employer'), ('renewal_worker', 'Renewal worker')], max_length=20, verbose_name='Call type'),
        ),
    ]
