# Generated by Django 5.2.1 on 2026-04-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0028_remove_active_from_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує модерації'), ('approved', 'Активна'), ('rejected', 'Скасована модератором'), ('closed', 'Закрита'), ('stopped', 'Пошук зупинено'), ('awaiting', 'Очікує оплати'), ('paid', 'Сплачено')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='vacancystatushistory',
            name='new_status',
            field=models.CharField(choices=[('pending', 'Очікує модерації'), ('approved', 'Активна'), ('rejected', 'Скасована модератором'), ('closed', 'Закрита'), ('stopped', 'Пошук зупинено'), ('awaiting', 'Очікує оплати'), ('paid', 'Сплачено')], max_length=20, verbose_name='New status'),
        ),
    ]
