# Generated by Django 5.2.1 on 2026-05-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0030_vacancy_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyuser',
            name='status',
            field=models.CharField(choices=[('creator', 'Creator'), ('administrator', 'Administrator'), ('owner', 'Owner'), ('member', 'Member'), ('pending_confirm', 'Pending confirmation'), ('restricted', 'Restricted'), ('left', 'Left'), ('kicked', 'Kicked'), ('ban', 'Ban'), ('unban', 'Unban')], default='member', max_length=20, verbose_name='Status'),
        ),
    ]
