# Generated by Django 5.2.1 on 2025-07-19 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_date_of_birth_user_birth_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
