# Generated by Django 5.2.1 on 2025-08-16 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userfeedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfeedback',
            options={'verbose_name': 'User feedback', 'verbose_name_plural': 'User feedbacks'},
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Any')], null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_given', to=settings.AUTH_USER_MODEL, verbose_name='Feedback author'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_received', to=settings.AUTH_USER_MODEL, verbose_name='Feedback recipient'),
        ),
    ]
