# Generated by Django 5.2.1 on 2025-08-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_userfeedback_options_user_gender_and_more'),
        ('work', '0002_alter_userworkprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWorkProfileInUser',
            fields=[
            ],
            options={
                'verbose_name': 'User work profile',
                'verbose_name_plural': 'User work profiles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('work.userworkprofile',),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], null=True, verbose_name='Gender'),
        ),
    ]
