# Generated by Django 5.2.1 on 2026-03-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_populate_auth_identities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWorkProfileInUser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_year',
        ),
    ]
