# Generated by Django 5.2.1 on 2026-03-29 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_birth_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('temporary', 'Тимчасове блокування'), ('permanent', 'Постійне блокування')], max_length=20, verbose_name='Block type')),
                ('reason', models.CharField(choices=[('manual', 'Ручне (адміністратор)'), ('rollcall_reject', 'Неявка на перекличку'), ('employer_uncheck', 'Зняття галочки замовником'), ('unpaid', 'Неоплачений рахунок'), ('other', 'Інше')], default='manual', max_length=30, verbose_name='Reason')),
                ('blocked_until', models.DateTimeField(blank=True, null=True, verbose_name='Blocked until')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks_issued', to=settings.AUTH_USER_MODEL, verbose_name='Blocked by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Блокування користувача',
                'verbose_name_plural': 'Блокування користувачів',
                'ordering': ['-created_at'],
            },
        ),
    ]
