# Generated by Django 5.2.1 on 2026-03-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_add_userblock_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='is_auto',
            field=models.BooleanField(default=False, verbose_name='Автоматичний'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='rating',
            field=models.CharField(choices=[('like', 'Лайк'), ('dislike', 'Дизлайк'), ('none', 'Без оцінки')], default='none', max_length=10, verbose_name='Оцінка'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
