# Generated by Django 5.2.1 on 2026-04-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_userfeedback_is_auto_userfeedback_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblock',
            name='reason',
            field=models.CharField(choices=[('manual', 'Ручне (адміністратор)'), ('rollcall_reject', 'Неявка на перекличку'), ('employer_uncheck', 'Зняття галочки замовником'), ('unpaid', 'Неоплачений рахунок'), ('employer_no_group', 'Замовник не зайшов у групу вакансії'), ('other', 'Інше')], default='manual', max_length=30, verbose_name='Reason'),
        ),
    ]
