# Generated by Django 5.2.1 on 2026-04-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_userblock_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Contact phone'),
        ),
    ]
