# Generated by Django 5.2.1 on 2026-06-03 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_add_employer_rollcall_fail_reason'),
        ('vacancy', '0031_alter_vacancyuser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerVoluntaryExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voluntary_exits', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancy.vacancy', verbose_name='Vacancy')),
            ],
            options={
                'verbose_name': 'Добровільний вихід',
                'verbose_name_plural': 'Добровільні виходи',
                'ordering': ['-created_at'],
            },
        ),
    ]
