# Generated by Django 5.2.1 on 2026-06-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_workervoluntaryexit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblock',
            name='reason',
            field=models.CharField(choices=[('manual', 'Ручне (адміністратор)'), ('rollcall_reject', 'Неявка на перекличку'), ('employer_uncheck', 'Зняття галочки замовником'), ('unpaid', 'Неоплачений рахунок'), ('employer_no_group', 'Замовник не зайшов у групу вакансії'), ('employer_rollcall_fail', 'Замовник не пройшов перекличку'), ('bot_blocked', 'Бот заблоковано користувачем'), ('other', 'Інше')], default='manual', max_length=30, verbose_name='Reason'),
        ),
    ]
