# Generated by Django 5.2.1 on 2026-06-12 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_userblock_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminHelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('closed', 'Closed'), ('timeout', 'Timeout')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('message_text', models.TextField(blank=True, default='', verbose_name='Message')),
                ('admin_chat_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='Admin chat message id')),
                ('media_message_ids', models.JSONField(blank=True, default=list, verbose_name='Media message ids')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_help_requests', to=settings.AUTH_USER_MODEL, verbose_name='Closed by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Admin help request',
                'verbose_name_plural': 'Admin help requests',
                'db_table': 'user_admin_help_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
