# Generated by Django 5.2.1 on 2025-06-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='has_bot_administrator',
            field=models.BooleanField(default=False, verbose_name='has bot administrator'),
        ),
    ]
