# Generated by Django 5.2.1 on 2025-06-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_channel_has_bot_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='invite_link',
            field=models.URLField(blank=True, null=True, verbose_name='Invite link'),
        ),
    ]
