# Generated by Django 5.2.1 on 2025-06-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_channel_invite_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('process', 'Process')], default='available', max_length=20),
        ),
    ]
