# Generated by Django 5.2.1 on 2025-06-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0005_group_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invite_link',
            field=models.URLField(blank=True, null=True, verbose_name='Invite link'),
        ),
    ]
