# Generated by Django 5.2.1 on 2025-06-25 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0006_group_invite_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='telegram_users', through='telegram.UserInGroup', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useringroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='telegram.group'),
        ),
        migrations.AlterField(
            model_name='useringroup',
            name='status',
            field=models.CharField(choices=[('creator', 'Creator'), ('administrator', 'Administrator'), ('member', 'Member'), ('restricted', 'Restricted'), ('left', 'Left'), ('kicked', 'Kicked'), ('ban', 'Ban'), ('unban', 'Unban')], default='member', max_length=20),
        ),
    ]
