# Generated by Django 5.2.1 on 2025-07-01 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0007_alter_group_users_alter_useringroup_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=32)),
                ('message_id', models.BigIntegerField()),
                ('content', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('deleted', 'Deleted'), ('delete_failed', 'Delete failed')], default='received', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='telegram.channel')),
            ],
        ),
    ]
