# Generated by Django 5.2.1 on 2025-07-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0008_channelmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='user',
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
