# Generated by Django 5.2.1 on 2025-07-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0009_remove_groupmessage_user_groupmessage_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
