# Generated by Django 5.2.1 on 2025-07-19 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0010_alter_groupmessage_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': 'Channel', 'verbose_name_plural': 'Channels'},
        ),
        migrations.AlterModelOptions(
            name='channelmessage',
            options={'verbose_name': 'Channel message', 'verbose_name_plural': 'Channel messages'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'verbose_name': 'Group message', 'verbose_name_plural': 'Group messages'},
        ),
        migrations.AlterModelOptions(
            name='useringroup',
            options={'verbose_name': 'User in group', 'verbose_name_plural': 'User in groups'},
        ),
    ]
