# Generated by Django 5.2.1 on 2025-07-21 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_alter_citytranslation_name'),
        ('telegram', '0011_alter_channel_options_alter_channelmessage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='city.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='channelmessage',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='telegram.channel', verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='channelmessage',
            name='content',
            field=models.JSONField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='channelmessage',
            name='content_type',
            field=models.CharField(max_length=32, verbose_name='Content type'),
        ),
        migrations.AlterField(
            model_name='channelmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='channelmessage',
            name='message_id',
            field=models.BigIntegerField(verbose_name='Message ID'),
        ),
        migrations.AlterField(
            model_name='channelmessage',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('deleted', 'Deleted'), ('delete_failed', 'Delete failed')], default='received', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('process', 'Process')], default='available', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='telegram_users', through='telegram.UserInGroup', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='content',
            field=models.JSONField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='content_type',
            field=models.CharField(max_length=32, verbose_name='Content type'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='telegram.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='message_id',
            field=models.BigIntegerField(verbose_name='Message ID'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('deleted', 'Deleted'), ('delete_failed', 'Delete failed')], default='received', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='useringroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='telegram.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='useringroup',
            name='status',
            field=models.CharField(choices=[('creator', 'Creator'), ('administrator', 'Administrator'), ('member', 'Member'), ('restricted', 'Restricted'), ('left', 'Left'), ('kicked', 'Kicked'), ('ban', 'Ban'), ('unban', 'Unban')], default='member', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='useringroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
