# Generated by Django 5.2.1 on 2025-07-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0012_alter_channel_city_alter_channel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmessage',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
