# Generated by Django 5.2.1 on 2025-08-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0013_channelmessage_extra_groupmessage_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='precheckoutlog',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
