# Generated by Django 5.2.1 on 2025-08-01 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0014_payment_extra_precheckoutlog_extra'),
        ('vacancy', '0020_alter_vacancy_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='vacancy',
            field=models.ForeignKey(blank=True, help_text="Заполняется из extra['vacancy_id']", null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancy.vacancy'),
        ),
    ]
