# Generated by Django 5.2.1 on 2025-08-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0015_payment_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useringroup',
            name='status',
            field=models.CharField(choices=[('creator', 'Creator'), ('administrator', 'Administrator'), ('owner', 'Owner'), ('member', 'Member'), ('restricted', 'Restricted'), ('left', 'Left'), ('kicked', 'Kicked'), ('ban', 'Ban'), ('unban', 'Unban')], default='member', max_length=20, verbose_name='Status'),
        ),
    ]
