# Generated by Django 5.2.1 on 2026-03-28 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0016_alter_useringroup_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='vacancy',
        ),
        migrations.DeleteModel(
            name='PreCheckoutLog',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
