# Generated by Django 5.2.1 on 2026-04-01 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0017_add_multi_city_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelmessage',
            options={'verbose_name': 'Повідомлення в каналі', 'verbose_name_plural': 'Повідомлення в каналах'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Група вакансії', 'verbose_name_plural': 'Групи вакансій'},
        ),
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'verbose_name': 'Повідомлення в групі', 'verbose_name_plural': 'Повідомлення в групах'},
        ),
        migrations.AlterModelOptions(
            name='useringroup',
            options={'verbose_name': 'Учасник групи', 'verbose_name_plural': 'Учасники груп'},
        ),
    ]
