# Generated by Django 5.2.1 on 2026-04-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0018_alter_channelmessage_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last used at'),
        ),
    ]
