from .registry import block_registry
from .implementations.channel_preview import ChannelPreviewBlock
from .implementations.active_vacancies_preview import ActiveVacanciesPreviewBlock
from .implementations.vacancy_create_form import VacancyCreateFormBlock