from .implementations.active_vacancies_preview import ActiveVacanciesPreviewBlock as ActiveVacanciesPreviewBlock
from .implementations.channel_preview import ChannelPreviewBlock as ChannelPreviewBlock
from .implementations.vacancy_create_form import VacancyCreateFormBlock as VacancyCreateFormBlock
from .registry import block_registry as block_registry
